export const SUPABASE_URL = 'https://wpxcspnugzmkllwedwgz.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndweGNzcG51Z3pta2xsd2Vkd2d6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEwNzUzNDcsImV4cCI6MjA5NjY1MTM0N30.RpT_-biT3zogGKJWE5b__QKRfJpnf-6qGbXLiTNnqkU';
